core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [ 
    path('',views.core,name='core')
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [ 
    path('',views.item,name='product'),
    path('product/<str:slug>/',views.product_detail,name='product_detail'),
    path('add/',views.add_item,name='add_product'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('product/',include('product.urls',namespace='product')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

product/models.py
from ast import Pass
from datetime import datetime
from distutils.command import upload
from email.mime import image
from email.policy import default
from pickle import TRUE
from random import choice
from re import T
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse

# Create your models here.






class Category(models.Model):
    name = models.CharField(max_length=50,default='')


    def __str__(self):
        return self.name

##ITEM
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(null=True,blank=True)
    category = models.ManyToManyField(Category)
    description = models.TextField()
    image = models.ImageField(upload_to='image_itrems/%y/%m/%d')
    slug = models.SlugField(null=True,blank=True)
    
    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.slug =slugify(self.title) 
        super(Item,self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('product:product_detail',kwargs={'slug':self.slug})

#### ORDER ITEM #####
class OrderItem(models.Model):
    Pass

    

    




    def __str__(self):
        return self.title


class OrderItem(models.Model):
    pass

    def __str__(self):
        return self.name


class OrderItem(models.Model):
    pass

    def __str__(self):
        return self.name

product/forms.py
from django import forms
from .models import Item


class AddItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title','price','discount_price','description','image','category']

core/views.py
from django.shortcuts import render
from product.models import Item
from django.core.paginator import Paginator
# Create your views here.
def core(request):
    product_list = Item.objects.all()
    paginator = Paginator(product_list,6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'product':page_obj}
    return render(request,'core/store.html',context)

product/views.py
from urllib import request
from django.shortcuts import render,redirect
from django.urls import reverse
from product.forms import AddItem
from .models import Item
from django.core.paginator import Paginator
# Create your views here.
def item(request):
    product_list = Item.objects.all()
    paginator = Paginator(product_list,9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # paginator = paginator+Paginator(product_list,3)
    context = {'product':page_obj,}
    return render(request,'product/products.html',context)





def product_detail(request,slug):
    product_detail = Item.objects.get(slug=slug)
    context = {'product':product_detail}
    return render(request,'product/products_detail.html',context)



def add_item(request):

    if request.method=='POST':
        form = AddItem(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('product:product'))

    else :
        form = AddItem()

    context = {'form':form}
    return render(request,'product/add_product.html',context)    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>cla</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
      <link rel="stylesheet" href="{% static 'cssjquery.fancybox.min.css' %}" media="screen">

   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="images/loading.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
{% include 'header.html' %}

{% block body %}


{% endblock body %}


    
{% include 'footer.html' %}

    
        <!-- Javascript files-->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
        <!-- sidebar -->
        <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
    </html>

templates/footer.html
{% load static %}

<footer>
    <div class="footer">
       <div class="container">
          <div class="row">
             <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <!-- <img class="logo1" src="{% static 'images/logo1.png' %}" alt="#"/> -->
                <ul class="social_icon">
                   <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                   <li><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                   <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                   <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
             </div>
             <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <h3>About Us</h3>
                <ul class="about_us">
                   <li>Ahmed Hamdy Saad<br> 22 years <br>faculty of engineering at NUB<br> BackEnd Developer</li>
                </ul>
             </div>
             <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <h3>Contact Us</h3>
                <ul class="conta">
                   <li>if you need any help,<br> contact <br>with us<br> in any time <br>Enjoy.... </li>
                </ul>
             </div>
             <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6">
                <form class="bottom_form">
                   <h3>Newsletter</h3>
                   <input class="enter" placeholder="Enter your email" type="text" name="Enter your email">
                   <button class="sub_btn">subscribe</button>
                </form>
             </div>
          </div>
       </div>
       <div class="copyright">
          <div class="container">
             <div class="row">
                <div class="col-md-12">
                   <p>© 2019 All Rights Reserved. Design by<a href="https://html.design/"> Free Html Templates</a></p>
                </div>
             </div>
          </div>
       </div>
    </div>
 </footer>

templates/header.html
{% load static %}
<header>
    <!-- header inner -->
    <div class="header">
       <div class="container-fluid">
          <div class="row">
             <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                <div class="full">
                   <div class="center-desk">
                      <div class="logo">
                         <a href="{% url 'core:core' %}"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                      </div>
                   </div>
                </div>
             </div>
             <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                <nav class="navigation navbar navbar-expand-md navbar-dark ">
                   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"></span>
                   </button>
                   <div class="collapse navbar-collapse" id="navbarsExample04">
                      <ul class="navbar-nav mr-auto">
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:core' %}">Home</a>
                         </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'product:product' %}">Products</a>
                         </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'product:add_product' %}">Add</a>
                         </li>
                         <!-- <li class="nav-item">
                            <a class="nav-link" href="computer.html">Category</a>
                         </li> -->
                         <!-- <li class="nav-item">
                            <a class="nav-link" href="laptop.html">Laptop</a>
                         </li> -->
                         
                         <li class="nav-item">
                            <a class="nav-link" href="contact.html">Contact Us</a>
                         </li>
                         <li class="nav-item">
                           <a href="#" class="nav-link waves-effect">
                              <span class="nav-link"><i class="fa-solid fa-cart-shopping"></i> Cart </span>
                           </a>
                         </li>
                         <li class="nav-item d_none">
                            <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                         </li>
                         <li class="nav-item d_none">
                            <a class="nav-link" href="#">Login</a>
                         </li>
                      </ul>
                   </div>
                </nav>
             </div>
          </div>
       </div>
    </div>
 </header>

templates/product/add_product.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}
<body>
    

    <br>

    <div class="col-lg-8 mx-auto">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            <center>
            <div class="inadd">
                <input class=" w-75 mt-3 mx-auto" type="submit" value="Add Item">
            </div>
            </center>
            
        </form>
    </div>

    <br>
</body>
{% endblock body %}

templates/product/buy.html
<form action=""></form>

templates/product/products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>cla</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
      <link rel="stylesheet" href="{% static 'cssjquery.fancybox.min.css' %}" media="screen">

   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="images/loading.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
{% include 'header.html' %}

   
         
            <h1 class="titleproduct p-3 mb-"><b>+{{product.paginator.count}} Products available</b></h1>
         
      
      <!-- end header inner -->
      <!-- end header -->
      <!-- products -->
      <div  class="products">
        <div class="container">
           <div class="row">
              <div class="col-md-12">
                 <div class="titlepage">
                    <h2>Our Products</h2>
                 </div>
              </div>
           </div>
           <div class="row">
              <div class="col-md-12">
                 <div class="our_products">

                  <br>
                    <div class="row">
                        {% for pro in product %}
                       <div class="col-md-4 margin_bottom1 mx-auto">
                          <div class="product_box">
                           <a href="{{pro.get_absolute_url}}"><h2><b>{{pro.title|upper}}</b></h2></a>
                            <figure><img src="{{pro.image.url}}" alt="sorry"/></figure><br>
                            <p class="lead">
                              {% if pro.discount_price %}
                              <span class="mr-1">
                                <del>Price: ${{ pro.price }}</del>
                              </span>
                              <span>Discount Price: ${{ pro.discount_price }}</span>
                              {% else %}
                              <span>Price: ${{ pro.price }}</span>
                              {% endif %}
                            </p>
                             <a href="{{pro.get_absolute_url}}"><h3>more details</h3></a>
                             <br>
                             <a href="{{ pro.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                              Add to cart
                              <i class="fas fa-shopping-cart ml-1"></i>
                            </a>
                            <a href="{{ pro.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                              Remove from cart
                            </a>
                          </div>
                         </div>
                         
                        {% endfor %}
                       </div>
                     <center>
                       {% if product.has_other_pages %}
                       
                           <div class="pagination col-lg-2 mx-auto">
                              <style>
                                 .pagination {
                                    text-align: center;
                                 }
                                 .pagination {
                                 display: inline-block;
                                 }

                                 .pagination a {
                                    color: black;
                                    float: left;
                                    padding: 8px 16px;
                                    text-decoration: none;
                                    transition: background-color .3s;
                                    border: 1px solid #ddd;
                                    margin: 0 4px;
                                 }

                                 .pagination a.active {
                                 background-color: #4CAF50;
                                 color: white;
                                 border: 1px solid #4CAF50;
                                 }

                                 .pagination a:hover:not(.active) {background-color: #ddd;}
                              </style>
                              
                                 <ul class="page-numbers">
                                    {% if product.has_previous %}
                                    <li><a href="?page={{product.previous_page_number}}"><i class="fa fa-angle-double-left"></i></a></li>
                                    {% endif %}
                                    
                                    {% for i in product.paginator.page_range %}
                                    <li><a href="?page={{i}}">{{i}}</a></li>
                                    {% endfor %}
                                    
                                    {% if product.has_next %}
                                    <li><a href="?page={{product.next_page_number}}"><i class="fa fa-angle-double-right"></i></a></li>
                                    {% endif %}
                                 </ul>
                           </div>
                        
                        {% endif %}
                        <!--                         
                       <div class="col-md-12">
                          <a class="read_more" href="">See More</a>
                       </div>
                        -->
                     </center>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </div>
      <!-- end products -->
      <!--  footer -->
      {% include 'footer.html' %}

      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>

templates/product/products_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>cla</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
      <link rel="stylesheet" href="{% static 'cssjquery.fancybox.min.css' %}" media="screen">

   </head>
   <!-- body -->
   <body class="main-layout inner_posituong computer_page">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="images/loading.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
{% include 'header.html' %}

      <!-- end header inner -->
      <!-- end header -->
      <!-- laptop1 -->
      <div class="laptop1">
         <div class="container">
            <div class="row">
               <div class="col-md-7">
                  <div class="laptop1_img">
                     <figure><img src="{{product.image.url}}" alt="#"/></figure>
                  </div>
               </div>
               <div class="col-md-5">
                  <div class="titlepage" align='left'>
                     <h2> {{ product.title }}</h2><br>
                     <div>
                        <h3 class="lead">
                        {% if product.discount_price %}
                        <h4 class="mr-1">
                          <del><b>Price: </b>${{ product.price }} </del>
                        </h4>
                        <h4><b>Discount Price: </b> ${{ product.discount_price }}</h4>
                        {% else %}
                        <h4><b>Price: </b>${{ product.price }} </span>
                        {% endif %}
                     </h3>
                  </div>
                     
                        <div class='mt-3'>
                           <h3><strong> Description:</strong></h3>
                           <p class='pt-0'>{{product.description}}</p>
                        </div>
                     
                      <br>
                        <div>
                           <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                              Add to cart
                              <i class="fas fa-shopping-cart ml-1"></i>
                           </a>
                           <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                              Remove from cart
                              </a>
                        </div>

                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end laptop1 -->
      <!--  footer -->
{% include 'footer.html' %}
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>